name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          mvn clean install
          mkdir artifacts && cp target/*.jar artifacts
          cd artifacts && ls
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-action-artifact
          path: artifacts
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: saqib1234
          password: Nasirmehm123
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: saqib1234/spring-boot-github-action-demo:latest
  deploy:
    needs: build
    runs-on: [aws-ec3]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: saqib1234
          password: Nasirmehm123
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
      - name: Pull Image from docker hub
        run: sudo docker pull saqib1234/spring-boot-github-action-demo:latest
      - name: Delete old container
        run: sudo docker rm -f spring-boot-app-container
      - name: Run Docker Image
        run: sudo docker run -d -p 8080:9091 --name spring-boot-app-container saqib1234/spring-boot-github-action-demo

#name: CI/CD Pipeline
#on:
#  push:
#    branches: [main]
#jobs:
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    steps:
#      - name : Checkout Source
#        uses: actions/checkout@v3
#      - name: Set up JDK
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#      - name: Build project
#        run: mvn clean install -DskipTests
#      - name: Login to docker hub
##        run: docker login -u ${{secrets.DOCKERUSERNAME}}  -p ${{secrets.DOCKERPASSWORD}}
#
##        run: docker login -u ${{secrets.DOCKERUSERNAME}}  -p ${{secrets.DOCKERPASSWORD}}
#        #        run:  echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#        run:  echo Nasirmehm123 | docker login -u saqib1234 --password-stdin
#      - name: build docker image
#        run: docker build -t saqib1234/aws3 .
#      - name: push docker image
#        run: docker push saqib1234/aws3:latest
#  deploy:
#    needs: build
#
#    runs-on: [aws-ec3]
#    steps:
#      #    - name: Login to docker hub
#            #        run:  echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#      #     run: echo Nasirmehm123 | docker login -u saqib1234 --password-stdin
#         - name: sudo pull image from docker hub
#           run: docker pull saqib1234/aws3:latest
#         - name: delete old docker container
#           run: docker rm -f saqibcontainer
#         - name: run docker container
#           run: docker run -d -p  8080:9091  --name saqibcontainer saqib1234/aws3:latest